# Generated by Django 6.1.1 on 2026-10-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('copyright', 'Copyright Terms'), ('terms', 'Terms and Conditions'), ('privacy', 'Privacy Policy')], max_length=50)),
                ('section_number', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['doc_type', 'section_number'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('section', models.CharField(choices=[('hampers', 'Hampers'), ('keychains', 'Key Chains'), ('wallets', 'Wallets')], default='wallets', max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('whatsapp_phone', models.CharField(default='916282119419', max_length=50)),
                ('in_stock', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['section', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('home_service', 'Home Service Card'), ('what_we_do', 'What We Do List Item'), ('media_service', 'AMDG Media & Designs Section'), ('design_item', 'Design Portfolio / Offerings')], default='what_we_do', max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link_url', models.CharField(blank=True, max_length=300)),
                ('button_label', models.CharField(blank=True, max_length=100)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='AMDG GROUP Ltd', max_length=200)),
                ('group_name', models.CharField(default='AMDG GROUP OF COMPANIES', max_length=200)),
                ('tagline', models.CharField(default='Creating Creativity', max_length=200)),
                ('bible_verse', models.TextField(default='“Commit to the Lord whatever you do, and he will establish your plans.” (Proverbs 16:3)')),
                ('phone_primary', models.CharField(default='+91 62822 68453', max_length=50)),
                ('phone_founder', models.CharField(default='+91 85905 27277', max_length=50)),
                ('email_primary', models.EmailField(default='groupamdg.india@gmail.com', max_length=254)),
                ('email_legal', models.EmailField(default='amdg.hub@gmail.com', max_length=254)),
                ('address', models.TextField(default='AMDG Digital Media · Pazhumattathil Buildings, Mar Sleeva Church, PO, Koodaranji, Calicut, Kerala 673604, India')),
                ('rating_score', models.CharField(default='★★★★★ · Media company', max_length=50)),
                ('review_url', models.URLField(default='https://g.page/r/CXyj8Py1eCl0EAE/review', max_length=500)),
                ('whatsapp_orders', models.CharField(default='916282119419', max_length=50)),
                ('whatsapp_support', models.CharField(default='916282268453', max_length=50)),
                ('facebook_url', models.URLField(default='https://facebook.com', max_length=500)),
                ('instagram_url', models.URLField(default='https://www.instagram.com/amdg_media.official/', max_length=500)),
                ('official_website', models.URLField(default='http://www.amdgmedia.co.in', max_length=500)),
                ('joy_mart_notice', models.TextField(default='Customers please note you can click the book now option and you will be directed to Whatsapp Chat and you can order your product and complete your order. Delivery within 7 Days of confirming order. TollFree No +91 62822 68453')),
                ('successful_deliveries', models.CharField(default='2204+', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('instagram_url', models.CharField(blank=True, max_length=500)),
                ('linkedin_url', models.CharField(blank=True, max_length=500)),
                ('whatsapp_url', models.CharField(blank=True, max_length=500)),
                ('facebook_url', models.CharField(blank=True, max_length=500)),
                ('twitter_url', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VisitorStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits_display', models.CharField(default='10K+', max_length=50)),
                ('today_visits_count', models.IntegerField(default=67)),
                ('last_increment_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
